
# Site settings
title: Your awesome title

# Build settings
include:
  - _pages/
  
plugins:
    - jekyll-postcss
  
postcss:
  cache: false
  
css_dir: "styles" # defaults to "css"

exclude:
  - tailwind.config.js
  - postcss.config.js
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - yarn.lock
  - yarn-error.log
  - .jekyll-cache/
